### DISCUSSION TITLE
Home Assistant Dashboard

### DISCUSSION THREAD

**Discussion by Vertikar** [aaronwmorris/indi-allsky#1335] [Show and tell]
Here's my current work in progress All Sky dashboard in Home Assistant.
 Thanks @aaronwmorris for dropping all the new sensor data into MQTT so quickly! Was going to ask if we could have that, but realised you'd already done it.

I'm using the Astroweather integration to get the deep sky information, and the air sensor temperature is coming from my existing weather station.

The Sky/Cloud temperature is coming from the MLX90614 sensor, which is a non-contact infrared thermometer.

I did have a SHT41 sensor inside the enclosure to see that temperature which is currently disconnected and showing 0 degrees in the bottom right side of the image.

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/f28a31e0-a84b-4efe-a629-d05e3c9573fb)

**Comment by aaronwmorris** [comment]
That looks awesome!  I tried to get the data populated in all the right places.  The last thing I need to work on for the sensor data is I am planning on allowing 2-3 user defined graphs on the Graph page for the sensor values.

**Reply by Vertikar** [reply]
Oh cool!

Was thinking could also improve on the Home Assistant discovery script too, wanted to have a look at the doco for that and see if I could add the entities under a device, and change the type of some of the values too, as they don't all get graphed within Home Assistant, think they're being treated as strings rather than integers.

An example is camera temperature, end up with the below color coded bar graph style, rather than a line graph

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/f7a9fc9a-3334-431d-8b7f-f0b908eb8223)


And here's the example of the line graph with moon altitude, I haven't changed anything to get it to do that either.

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/8cd0bbdd-dd2f-483c-ae82-91e8264ff1d4)

**Reply by aaronwmorris** [reply]
Very nice.  FYI, the reason the moon altitude has a slight bump just below 0 degrees altitude is due to the atmospheric diffraction calculations in pyephem

I did notice the weird graph styles during my testing, but I did not dig too deep on what causes that.

**Reply by Anpo-git** [reply]
<img width="1655" height="1027" alt="Screenshot 2026-03-24 195217" src="https://github.com/user-attachments/assets/75301f79-2715-4cd0-b126-230aa7e79c94" />
Yes, Home Assistant is really cool, I finished my dashboard today.

**Reply by Vertikar** [reply]
>  Yes, Home Assistant is really cool, I finished my dashboard today.

Love it @Anpo-git 
What are you using to source your data, I can see lightning in there, is that from Blitzortung? Are you getting K-P from allsky?

**Reply by Anpo-git** [reply]
> What are you using to source your data, I can see lightning in there, is that from Blitzortung? Are you getting K-P from allsky?

Hi, yes, all the values ​​come from the camera, including the lightning readings.

I've installed the AS3935 sensor, but unfortunately I haven't had a thunderstorm yet to test it properly.

**Comment by astrotater** [comment]
@Vertikar can you show a pic of how you integrated your MLX90614? 
I've found some examples online, but one discussion on Facebook a guy said he had his ML90614 get destroyed by water damage. But I've seen plenty others with the MLX90614 waterproofed and functioning fine. Makes me wonder if the Facebook was a bad installation or a faulty seal. 

> Here's my current work in progress All Sky dashboard in Home Assistant. Thanks @aaronwmorris for dropping all the new sensor data into MQTT so quickly! Was going to ask if we could have that, but realised you'd already done it.
> 
> I'm using the Astroweather integration to get the deep sky information, and the air sensor temperature is coming from my existing weather station.
> 
> The Sky/Cloud temperature is coming from the MLX90614 sensor, which is a non-contact infrared thermometer.
> 
> I did have a SHT41 sensor inside the enclosure to see that temperature which is currently disconnected and showing 0 degrees in the bottom right side of the image.
> 
> ![image](https://private-user-images.githubusercontent.com/436414/340916538-f28a31e0-a84b-4efe-a629-d05e3c9573fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzU4NTIsIm5iZiI6MTcxOTA3NTU1MiwicGF0aCI6Ii80MzY0MTQvMzQwOTE2NTM4LWYyOGEzMWUwLWE4NGItNGVmZS1hNjI5LWQwNWUzYzk1NzNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjU5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDYxZDU5Mzk4MWNiZjZhOWMzNGIxMGIyYmY1NmMxOTBhNGM3ZTY4NTE4MTAzNWMyZGUxOGI1MzNlYThkYzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3TauF-m6y2aglyJqYSEOq59PDCRcnT6fLRzql299qoM)

**Reply by Vertikar** [reply]
It's currently in a very thin ziplock bag, I'm still testing it and sorting out my permanent enclosure.

It seems like it should work behind a thin sheet of Acrylic or Polycarbonate, but i think behind the camera dome might be pushing it.

I had a read of similar things suggesting its hermetically sealed, but i didn't notice that in the data sheet.
Also figured its easier to clean or replace an IR clear cover over it than the full sensor if something does happen

**Reply by Vertikar** [reply]
Here's a photo of my current testing setup... not weather proof, but water resistant

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/3a551815-ca2f-4cd9-a970-74ab89a79f74)

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/03399567-018d-4865-86f2-3fb79e61aac2)

![image](https://github.com/aaronwmorris/indi-allsky/assets/436414/b091fd9a-3208-4788-9921-9de14b2edcb9)


Final plan is likely to be inside some PVC pipe, but I'm still not settled on that. Also thinking about a portable setup
I've seen a lot of people moving to inside the waterproof box style enclosure, which might be lighter and easier to mount in some cases.

My thoughts are that the TSL light sensor should sit inside the camera dome, not sure if anyone else has tried this yet, but I know @aaronwmorris mentioned he was testing the TSL2591 and had it hooked up still a few days ago.

**Comment by astrotater** [comment]
I wonder if sealing the outer metal ring of the sensor against the body with silicone, as well as using something like a 25g or 22g needle and carefully creating a fillet of silicone seal where the sensor eye meets the metal body, would ensure that its waterproof.
Silicone will also flex a little with the changing seasons. 

![Screenshot 2024-06-23 at 10 44 27 AM](https://github.com/aaronwmorris/indi-allsky/assets/171597037/f20b0c84-71a6-4f12-ab9a-579318fb9c9f)

**Comment by astrotater** [comment]
The Melexis spec sheet has the bandpass of the window of the sensor at 5.5 to 14μm. 

According to Edmund Optics, the following glass will pass that wavelength:
Germanium, Zinc Selenide, Sodium Chloride, and Potassium Bromide. 

https://www.edmundoptics.com/knowledge-center/application-notes/optics/the-correct-material-for-infrared-applications/

Looks like polymer films aren't the greatest within that wavelength. Although Edmund advertises them as being ideal for IR applications. Could be worth a shot. 
https://www.edmundoptics.com/f/infrared-ir-material-windows/12440/

These look to be the best transmission, but it won't work for us:  KBr is water soluble, and its surfaces should be protected from exposure to moisture. Exposure to moisture will degrade the surface of the window.
https://www.edmundoptics.com/f/potassium-bromide-kbr-windows/14168/

These are slightly cheaper, looks like they start to have some falloff around 14μm. But they also won't work outdoors since they're hydroscopic. 
https://www.edmundoptics.com/f/sodium-chloride-nacl-windows/14170/

Here's the graph for the TSL2591, 0.4μm to 1.1μm. I have a piece of 15mm sapphire glass for it, which according to Edmund Optics, should work fine. 

![rK4bo](https://github.com/aaronwmorris/indi-allsky/assets/171597037/83451dff-5634-4ff3-b489-c073e3972bae)

**Reply by Vertikar** [reply]
Interesting, thanks for digging that up, I was going to have a look and try and find some details on it.

After running it in the ziplock bag for a few days it actually seemed relatively accurate. I haven't planned on how to mount it near the camera yet, but thinking under glass still or even plastic, just something easy and relatively cheap.

I did find some watch sapphire glass on ebay too - https://www.ebay.com.au/itm/233659151380 but at that price I'm not sure if its actual sapphire.

**Comment by astrotater** [comment]
Looks like in 2015, Melexis switched from germanium lens to silicon lens. 

![Screenshot 2024-06-23 at 12 58 58 PM](https://github.com/aaronwmorris/indi-allsky/assets/171597037/61f2fc8f-d9cf-42ff-b4ea-1ea63bb52331)

**Comment by gaitskell** [comment]
@Vertikar Is there a current page that describes the steps to link Home Assistant to indi allsky and how to configure? My thanks,

**Reply by Vertikar** [reply]
Yep, this should cover most of it, Aaron has already put together a good wiki page on it.
https://github.com/aaronwmorris/indi-allsky/wiki/MQTT-Broker-Publishing

Anything else just ask here and I'll try and answer if I can or Aaron will chime in

**Reply by gaitskell** [reply]
@vertikar Thanks for guidance. I setup MQTT in #HASS (Home Assistant) and #indi-alllsky. However, I think I have a very basic misconception. In the #indi-alllsky -> #HASS solution is the broker running on #HASS? and #indi-alllsky should be broacasting to that broker? No need for a local broker on indi-allsky machine.

**Reply by aaronwmorris** [reply]
@gaitskell You can use your existing broker if you already have one.  You could even have multiple indi-allsky systems all using the same broker, as long as each system is using a unique base topic.

**Comment by johntdyer** [comment]
@Vertikar  - Could you share the JSON / Yaml for your dashboard for us to model off of?

**Reply by Vertikar** [reply]
Here's my YAML, but I suspect @Anpo-git would have a lot better one to model off, his dashboard he shared up higher - https://github.com/aaronwmorris/indi-allsky/discussions/1335#discussioncomment-16297846 is using the new HA dashboards and looks way nicer than mine!

For reference I've got the astroweather custom integration installed via HACS, and my current weather conditions come from a local weather station

```
theme: Backend-selected
title: AllSky
path: allsky
badges: []
cards:
  - type: entities
    entities:
      - entity: sensor.indi_allsky_moon_altitude
      - entity: binary_sensor.night
      - entity: sensor.indi_allsky_stars
      - entity: sensor.indi_allsky_sqm
      - entity: sensor.indi_allsky_sun_altitude
      - entity: binary_sensor.moon_mode
  - type: entities
    entities:
      - entity: sensor.indi_allsky_cpu_total
      - entity: sensor.indi_allsky_thermal_cpu_thermal_0
      - entity: sensor.indi_allsky_filesystem
  - type: picture
    image_entity: image.indi_allsky_indi_allsky_camera
  - type: entities
    entities:
      - entity: binary_sensor.astroweather_vic_deep_sky_view
      - entity: sensor.astroweather_vic_darkness
      - entity: sensor.astroweather_deepsky_forecast_today_description
  - type: entities
    entities:
      - entity: sensor.indi_allsky_camera_temp
      - entity: sensor.air_ar_00001924_temperature_2
      - entity: sensor.sensor_user_25
      - entity: sensor.sensor_user_26
      - entity: sensor.air_ar_00001924_dew_point_2
      - entity: sensor.tempest_st_00024431_dew_point_2
  - type: entities
    entities:
      - entity: sensor.sensor_user_10
      - entity: sensor.sensor_user_11
      - entity: sensor.sensor_user_7
      - entity: sensor.sensor_user_16
      - entity: sensor.sensor_user_17
      - entity: sensor.sensor_user_18
      - entity: sensor.sensor_user_19
```
